name: Build and Publish Docusaurus site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd website
          npm ci
      - name: Build site
        run: |
          cd website
          npm run build
      - name: Add CNAME (optional)
        if: ${{ secrets.GH_PAGES_CNAME != '' }}
        run: |
          echo "${{ secrets.GH_PAGES_CNAME }}" > website/build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish to the gh-pages branch (default), change publish_branch if needed
          publish_branch: gh-pages
          publish_dir: ./website/build
